language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo build --release --verbose
  - cargo test --verbose
