language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

env:
  global:
    - secure: aeE2+kAuMxMFl43OIBgHf2pF5qSoyOzyIChhp3gocpP+RtS68D5WeDDQWj3oFjKosZ9QKzZhntq9AdzAzswtD/6lX/TWAdE8vrDzDwhRqjmOUaGCMj1tL4aFPxbZuyNKtQrsOQ+fbRIwulYPuMWfCKRy43v0wD/+W30E9ZysVrzt2Y0zxSPgmJJEq4LSJRKZ26//cFk/R4lABu9VpH6HYWTK1SRlabHxnpWcQdeSofjGsPm/HWxd2mS5Wxdn2uMwHzdQBCZ8Z3nUy0tQpwhK6bMy7Df3ffvz1B3ttATOq112yQCbDw9XFJ4HnkSlgSd9Eyc4HUOPjY2xbz38SpoJfT29yCUOdfayryFDvFJPlXH1P9s7iq+ZxUJwz9Cr+0zsN+fFe8TyPOwenjgPJ11xohEvX3iKYf2z3Kt0aLUE59CokHYsxFn1BnuI+UV40aVaC80EgYSC9FAJRQG4RRiH8NHW/CfMtl9lMoMtSsm9YImnyISQLfqQwYBx/nJT07jFqyfONCuqSErX4dYNAHJB1NxWQ0q6vcC/lHvtV14g58NqR8y+N/hwpyMGWuCpa715CaJx+yw1QjgKy2iDvKltQuKmA+sGYcLetdUuuLjP/oSVmU4quxJr1EAZP5h6SkTjf/14Tv4MMtXXCTiy5ybbe5ND0Y4h4Atc8iniAlMYmeA=
    - secure: rMU590nAggJr3wB0tBldZdXB46dBK1UfFwMByuyYPJlYx7skao8MVJBS2sbTMiRUUiVF2LsoM2YYuoTRG5FiieXjeH/I8nvI5mpKlkPJounmontSh2zhxfK/NrQihZqZQsLrn7cDra4Ldtz9E7L2ydfj7xskAaeEO1GynCK7Q+UCMSl/HRXEVf4bv2VONzN1k61H9h7d6rk1JF4J5iZkvhvt+j3zWusiO0Y5s8/cj4ZWaXSPyoZUjdaHjwe3P89eXnoGVN8b3cMsXSxZJXxeiPTDp1V81lqsMMHHJdc75LDQujWm9l982ygpljpeaLs7xq8Y5HGWU0vBXlyQA5Xgt02s4Yz+YQ5ABldFsZXD/FQu3R0DfJumNYYoW8GWgJpE9AMYj+ZKsSUZgNxKzAVYsXC/mZXuBDS1hiCDaQSl/3XUqVGjs92GVWBKk1p9qjnTQzDnk8VOCxFSw3le0q7GrPOdm7L1ZrIdVg0Wl/BuBX2CTMUsFJDAbR/J8Fjywl3+p4pDk1hF9ewX7Xl3+TKXwg6CVXmi5cTJXZxdYe6RI+tDfX0DCuvQBiwBJESXhyeLQYI/9wWjzmcBzdqUrULc48xY6sOMmNlJwzVg6FLn7x/1IeNUTcvs51P2VOmYPwDZFt6+m4scoeAD7qvOxaoVD49jI+7TipeR/gHaQj/wpOE=

script:
  - cargo build --release --verbose
  - cargo test --verbose

before_deploy:
  - cargo package --verbose
  - cargo doc --release --verbose
  - ./save_credentials.sh "$TRAVIS_REPO_SLUG"

deploy:
  provider: script
  script: ./deploy.sh "$TRAVIS_TAG"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
